;; binary search
(define-module (praxis binary-search)
  #:use-module (srfi srfi-64)
  #:export (binary-search))

(test-begin "bin-search")

(define (binary-search num lis)
  (define (bsearch low high)
    (let* ((mix (floor (/ (+ low high) 2)))
           (mid (list-ref lis mix)))
      (cond ((or (> low high)
                 (and (eq? low high)
                      (not (eq? mid num)))) -1)
            ((eq? num mid) mix)
            ((> num mid) (bsearch (+ 1 mix) high))
            (else (bsearch low mix)))))
  (bsearch 0 (- (length lis) 1)))

(define asc-lis '(1 5 5 16 29 42 45 55 55 59 64 70 74 77 88 91 92 94))
(define asc-list '(1 5 5 16 29 42 45 55 55 59 64 70 74 77 88 91 92 94 95))
(define asc-liste '(1 5 5 16 29 42 45 55 55 59 64 70 74 77 88 91 92 94 95 99))

(test-eq 0 (binary-search 1 asc-lis))
(test-eq 2 (binary-search 5 asc-lis))
(test-eq 3 (binary-search 16 asc-lis))
(test-eq 4 (binary-search 29 asc-lis))
(test-eq 9 (binary-search 59 asc-lis))
(test-eq 11 (binary-search 70 asc-lis))
(test-eq 12 (binary-search 74 asc-lis))
(test-eq 14 (binary-search 88 asc-lis))
(test-eq 16 (binary-search 92 asc-lis))
(test-eq 17 (binary-search 94 asc-lis))
(test-eq -1 (binary-search -5 asc-lis))
(test-eq -1 (binary-search 15 asc-lis))
(test-eq -1 (binary-search -20 asc-lis))
(test-eq -1 (binary-search 200 asc-lis))

(test-eq 0 (binary-search 1 asc-list))
(test-eq 2 (binary-search 5 asc-list))
(test-eq 3 (binary-search 16 asc-list))
(test-eq 4 (binary-search 29 asc-list))
(test-eq 9 (binary-search 59 asc-list))
(test-eq 11 (binary-search 70 asc-list))
(test-eq 12 (binary-search 74 asc-list))
(test-eq 14 (binary-search 88 asc-list))
(test-eq 16 (binary-search 92 asc-list))
(test-eq 17 (binary-search 94 asc-list))
(test-eq 18 (binary-search 95 asc-list))
(test-eq -1 (binary-search -5 asc-list))
(test-eq -1 (binary-search 15 asc-list))
(test-eq -1 (binary-search -20 asc-list))
(test-eq -1 (binary-search 200 asc-list))

(test-eq 0 (binary-search 1 asc-liste))
(test-eq 2 (binary-search 5 asc-liste))
(test-eq 3 (binary-search 16 asc-liste))
(test-eq 4 (binary-search 29 asc-liste))
(test-eq 9 (binary-search 59 asc-liste))
(test-eq 11 (binary-search 70 asc-liste))
(test-eq 12 (binary-search 74 asc-liste))
(test-eq 14 (binary-search 88 asc-liste))
(test-eq 16 (binary-search 92 asc-liste))
(test-eq 17 (binary-search 94 asc-liste))
(test-eq 18 (binary-search 95 asc-liste))
(test-eq 19 (binary-search 99 asc-liste))
(test-eq -1 (binary-search -5 asc-liste))
(test-eq -1 (binary-search 15 asc-liste))
(test-eq -1 (binary-search -20 asc-liste))
(test-eq -1 (binary-search 200 asc-liste))

(test-end "bin-search")
